name: face_recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - setuptools
  - pip
  - wheel
  - jupyterlab=4.4.4
  - cpuonly
  - ipywidgets
  - mamba
  - cmake
  - dlib
  - face_recognition
  - pip:
      - matplotlib==3.6.2
      - numpy==1.23.5
      - scikit-learn==1.3.0

