name: face_recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyterlab=4.4.4
  - ipywidgets
  - dlib
  - matplotlib
  - numpy==1.23.5
  - scikit-learn==1.3.0
  - pip:
    - face_recognition 

