name: face_recognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - jupyterlab=4.4.4
  - ipywidgets
  - dlib
  - pip:
      -face_recognition 
      - matplotlib==3.6.2
      - numpy==1.23.5
      - scikit-learn==1.3.0


